[package]

name = "mime_guess"
version = "1.2.0"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]
license = "MIT"
description = "A simple crate for detection of a file's MIME type by its extension."
keywords = ["mime", "filesystem", "extension"]
repository = "https://github.com/cybergeek94/mime_guess"

[features]
bench = []

[dependencies]
mime = "0.1"
