[package]

name = "mime_guess"
version = "1.6.1"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]
license = "MIT"
description = "A simple crate for detection of a file's MIME type by its extension."
keywords = ["mime", "filesystem", "extension"]
repository = "https://github.com/cybergeek94/mime_guess"

build = "src/gen_mime_types.rs"

[features]
bench = []

[dependencies]
mime = ">=0.1, <0.3"
phf = { version = "0.7", features = ["unicase"] }
unicase = "1.1"

[build-dependencies]
phf_codegen = "0.7"
unicase = "1.1"
