[package]

name = "mime_guess"
version = "1.0.0"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]
license = "MIT"
description = "A simple crate for detection of a file's MIME type by its extension."
keywords = ["mime", "filesystem", "extension"]


[dependencies]
mime = "*"
